import React, { useEffect, useState, useRef } from 'react';
import { useParams } from 'react-router';
import { getDb } from '../lib/db';
import DocumentViewer from '../components/DocumentViewer';
import { invoke } from '@tauri-apps/api/core';
import { convertFileSrc } from '@tauri-apps/api/core';

// 1. Define the TypeScript interfaces matching your Rust structs
export interface BoundingBox {
    left: number;
    top: number;
    width: number;
    height: number;
}

export interface OcrWord {
    text: string;
    confidence: number;
    box_coords: BoundingBox;
}

export interface DocumentPageResult {
    image_path: string; // Path to the PNG generated by Rust
    natural_width: number;
    natural_height: number;
    words: OcrWord[];
    text: string; // The aggregated full text
}

export interface ExtractionResult {
    session_id: string;
    pages: DocumentPageResult[];
}

const parseTsvToCleanLines = (rawTsv: string): string[] => {
    const rows = rawTsv.trim().split('\n');
    const dataRows = rows.slice(1); // Skip the header row

    let currentLine = "";
    const formattedLines: string[] = [];

    dataRows.forEach(row => {
        const cols = row.split('\t');
        if (cols.length < 12) return;

        const level = cols[0];
        const text = cols[11]?.trim();

        // Level 4 indicates a new line in the document
        if (level === '4') {
            if (currentLine) {
                formattedLines.push(currentLine);
                currentLine = "";
            }
        } 
        // Level 5 indicates a word
        else if (level === '5' && text) {
            currentLine += (currentLine ? " " : "") + text;
        }
    });

    if (currentLine) {
        formattedLines.push(currentLine);
    }

    return formattedLines;
};

export default function Session(): React.ReactElement {
    const { id } = useParams<{ id: string }>();

    // Layout State
    const [leftWidth, setLeftWidth] = useState(50);
    const containerRef = useRef<HTMLDivElement>(null);
    const isDragging = useRef(false);

    // Data State
    const [isLoading, setIsLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [fileUrl, setFileUrl] = useState<string | null>(null);
    const [extractionResult, setExtractionResult] = useState<ExtractionResult | null>(null);

    // Track started processing document to avoid issues with calling processDocument multiple times
    const hasProcessed = useRef(false);

    // 2. Fetch the file path from the DB, then pass it to Rust for processing
    useEffect(() => {
        async function processDocument() {
            if (!id) return;

            // Prevent double-execution in Strict Mode
            if (hasProcessed.current) return;
            hasProcessed.current = true;

            try {
                setError(null);
                setExtractionResult(null);
                setFileUrl(null);
                setIsLoading(true);
                const db = await getDb();

                // A. Check for cached OCR results in the database first
                const cachedPages = await db.select<{
                    image_path: string;
                    natural_width: number;
                    natural_height: number;
                    full_text: string;
                    words_json: string;
                }[]>(
                    'SELECT image_path, natural_width, natural_height, full_text, words_json FROM document_pages WHERE session_id = $1 ORDER BY page_index ASC',
                    [id]
                );

                if (cachedPages && cachedPages.length > 0) {
                    console.log("Restoring OCR results from cache...");
                    
                    const restoredPages: DocumentPageResult[] = cachedPages.map(page => ({
                        image_path: page.image_path,
                        natural_width: page.natural_width,
                        natural_height: page.natural_height,
                        text: page.full_text,
                        words: JSON.parse(page.words_json)
                    }));

                    setExtractionResult({ session_id: id, pages: restoredPages });
                    setFileUrl(convertFileSrc(restoredPages[0].image_path));
                    return; // Exit early, no need to invoke Rust
                }

                // B. If no cache exists, query the files table for the original file
                const dbResult = await db.select<{ file_path: string }[]>(
                    'SELECT file_path FROM files WHERE session_id = $1 LIMIT 1',
                    [id]
                );

                if (!dbResult || dbResult.length === 0) {
                    throw new Error('No document attached to this session.');
                }

                const originalFilePath = dbResult[0].file_path;

                // C. Invoke the Rust backend to render the PDF to an image and run OCR
                console.log("Processing document via Rust backend...");
                const rustResult = await invoke<ExtractionResult>('process_document', {
                    sessionId: id,
                    filePath: originalFilePath
                });

                // D. Cache the result into the database for next time
                for (let i = 0; i < rustResult.pages.length; i++) {
                    const page = rustResult.pages[i];
                    await db.execute(
                        `INSERT INTO document_pages (id, session_id, page_index, image_path, natural_width, natural_height, full_text, words_json) 
                         VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
                        [
                            crypto.randomUUID(),
                            id,
                            i,
                            page.image_path,
                            page.natural_width,
                            page.natural_height,
                            page.text,
                            JSON.stringify(page.words)
                        ]
                    );
                }

                setExtractionResult(rustResult);

                // E. Convert the new PNG image path returned by Rust into a displayable URL
                if (rustResult.pages.length > 0) {
                    setFileUrl(convertFileSrc(rustResult.pages[0].image_path));
                }
                
            } catch (err) {
                console.error("Backend processing failed:", err);
                setError(err instanceof Error ? err.message : 'Failed to process document.');
                // Only allow a retry if the backend actually threw an error
                hasProcessed.current = false; 
            } finally {
                // ALWAYS turn off the loading state when finished
                setIsLoading(false);
            }
        }

        processDocument();

    }, [id]);

    // 3. Global mouse event handlers for smooth dragging
    useEffect(() => {
        const handleMouseMove = (e: MouseEvent) => {
            if (!isDragging.current || !containerRef.current) return;

            const containerRect = containerRef.current.getBoundingClientRect();
            const newWidth = ((e.clientX - containerRect.left) / containerRect.width) * 100;

            if (newWidth >= 20 && newWidth <= 80) {
                setLeftWidth(newWidth);
            }
        };

        const handleMouseUp = () => {
            if (isDragging.current) {
                isDragging.current = false;
                document.body.style.cursor = 'default';
            }
        };

        document.addEventListener('mousemove', handleMouseMove);
        document.addEventListener('mouseup', handleMouseUp);

        return () => {
            document.removeEventListener('mousemove', handleMouseMove);
            document.removeEventListener('mouseup', handleMouseUp);
        };
    }, []);

    const handleMouseDown = () => {
        isDragging.current = true;
        document.body.style.cursor = 'col-resize';
    };

    // Get the first page data for rendering
    const activePage = extractionResult?.pages[0];

    return (
        <main className="relative flex h-full w-full overflow-hidden bg-background">
            <div className="flex h-full w-full" ref={containerRef}>

                {/* === LEFT SIDE: File Viewer === */}
                <div
                    className="flex h-full flex-col bg-surface-container-lowest transition-[width] duration-0"
                    style={{ width: `${leftWidth}%` }}
                >
                    <div className="border-b border-outline-variant p-4">
                        <h2 className="font-headline-sm text-primary">Source Document</h2>
                    </div>

                    <div className="flex flex-1 overflow-hidden">
                        {isLoading ? (
                            <div className="flex w-full items-center justify-center text-on-surface-variant">Processing with local AI...</div>
                        ) : error ? (
                            <div className="flex w-full items-center justify-center text-error">{error}</div>
                        ) : fileUrl && activePage ? (
                            // Pass both the image URL and the pre-calculated words down
                            <DocumentViewer
                                fileUrl={fileUrl}
                                words={activePage.words}
                            />
                        ) : null}
                    </div>
                </div>

                {/* === THE DRAGGABLE DIVIDER === */}
                <div
                    className="group relative flex w-3 cursor-col-resize items-center justify-center transition-colors hover:bg-primary/10 active:bg-primary/20"
                    onMouseDown={handleMouseDown}
                >
                    <div className="h-12 w-1 rounded-full bg-outline-variant transition-colors group-hover:bg-primary group-active:bg-primary" />
                </div>

                {/* === RIGHT SIDE: Extraction Workspace === */}
                <div
                    className="flex h-full flex-col p-6 transition-[width] duration-0"
                    style={{ width: `${100 - leftWidth}%` }}
                >
                    <div className="mb-4">
                        <h1 className="font-headline-sm text-primary">Document Text</h1>
                    </div>

                    <div className="flex-1 overflow-auto rounded-2xl border border-outline-variant bg-surface-bright px-8 py-10 shadow-sm">
                        {isLoading ? (
                            <div className="flex h-full items-center justify-center font-body-md text-on-surface-variant">
                                Awaiting extraction...
                            </div>
                        ) : activePage && activePage.text ? (
                            <div className="space-y-2 font-body-md text-on-surface leading-relaxed">
                                {parseTsvToCleanLines(activePage.text).map((line, index) => (
                                    <p key={index} className="min-h-[1.5rem]">
                                        {line}
                                    </p>
                                ))}
                            </div>
                        ) : (
                            <div className="flex h-full items-center justify-center font-body-md text-on-surface-variant">
                                No readable text found.
                            </div>
                        )}
                    </div>
                </div>

            </div>
        </main>
    );
}