import React, { useEffect, useState, useRef } from 'react';
import { useParams } from 'react-router';
import { getDb } from '../lib/db';
import DocumentViewer from '../components/DocumentViewer';
import { invoke } from '@tauri-apps/api/core';
import { convertFileSrc } from '@tauri-apps/api/core';

// 1. Define the TypeScript interfaces matching your Rust structs
export interface BoundingBox {
    left: number;
    top: number;
    width: number;
    height: number;
}

export interface OcrWord {
    text: string;
    confidence: number;
    box_coords: BoundingBox;
}

export interface DocumentPageResult {
    image_path: string; // Path to the PNG generated by Rust
    natural_width: number;
    natural_height: number;
    words: OcrWord[];
    text: string; // The aggregated full text
}

export interface ExtractionResult {
    session_id: string;
    pages: DocumentPageResult[];
}

export default function Session(): React.ReactElement {
    const { id } = useParams<{ id: string }>();

    // Layout State
    const [leftWidth, setLeftWidth] = useState(50);
    const containerRef = useRef<HTMLDivElement>(null);
    const isDragging = useRef(false);

    // Data State
    const [isLoading, setIsLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [fileUrl, setFileUrl] = useState<string | null>(null);
    const [extractionResult, setExtractionResult] = useState<ExtractionResult | null>(null);

    // 2. Fetch the file path from the DB, then pass it to Rust for processing
    useEffect(() => {
        let isMounted = true;

        async function processDocument() {
            if (!id) return;
            
            try {
                setError(null);
                setExtractionResult(null);
                setFileUrl(null);
                setIsLoading(true);
                const db = await getDb();
                
                // A. Query the files table for the original file (e.g., the raw PDF)
                const dbResult = await db.select<{ file_path: string }[]>(
                    'SELECT file_path FROM files WHERE session_id = $1 LIMIT 1',
                    [id]
                );

                if (!dbResult || dbResult.length === 0) {
                    throw new Error('No document attached to this session.');
                }

                const originalFilePath = dbResult[0].file_path;

                // B. Invoke the Rust backend to render the PDF to an image and run OCR
                const rustResult = await invoke<ExtractionResult>('process_document', {
                    sessionId: id,
                    filePath: originalFilePath
                });

                if (isMounted) {
                    setExtractionResult(rustResult);
                    
                    // C. Convert the new PNG image path returned by Rust into a displayable URL
                    if (rustResult.pages.length > 0) {
                        setFileUrl(convertFileSrc(rustResult.pages[0].image_path));
                    }
                }
            } catch (err) {
                console.error("Backend processing failed:", err);
                if (isMounted) {
                    setError(err instanceof Error ? err.message : 'Failed to process document.');
                }
            } finally {
                if (isMounted) setIsLoading(false);
            }
        }

        processDocument();

        return () => {
            isMounted = false;
        };
    }, [id]);

    // 3. Global mouse event handlers for smooth dragging
    useEffect(() => {
        const handleMouseMove = (e: MouseEvent) => {
            if (!isDragging.current || !containerRef.current) return;

            const containerRect = containerRef.current.getBoundingClientRect();
            const newWidth = ((e.clientX - containerRect.left) / containerRect.width) * 100;

            if (newWidth >= 20 && newWidth <= 80) {
                setLeftWidth(newWidth);
            }
        };

        const handleMouseUp = () => {
            if (isDragging.current) {
                isDragging.current = false;
                document.body.style.cursor = 'default';
            }
        };

        document.addEventListener('mousemove', handleMouseMove);
        document.addEventListener('mouseup', handleMouseUp);

        return () => {
            document.removeEventListener('mousemove', handleMouseMove);
            document.removeEventListener('mouseup', handleMouseUp);
        };
    }, []);

    const handleMouseDown = () => {
        isDragging.current = true;
        document.body.style.cursor = 'col-resize';
    };

    // Get the first page data for rendering
    const activePage = extractionResult?.pages[0];

    return (
        <main className="relative flex h-full w-full overflow-hidden bg-background">
            <div className="flex h-full w-full" ref={containerRef}>

                {/* === LEFT SIDE: File Viewer === */}
                <div 
                    className="flex h-full flex-col bg-surface-container-lowest transition-[width] duration-0" 
                    style={{ width: `${leftWidth}%` }}
                >
                    <div className="border-b border-outline-variant p-4">
                        <h2 className="font-headline-sm text-primary">Source Document</h2>
                    </div>
                    
                    <div className="flex flex-1 overflow-hidden">
                        {isLoading ? (
                            <div className="flex w-full items-center justify-center text-on-surface-variant">Processing with local AI...</div>
                        ) : error ? (
                            <div className="flex w-full items-center justify-center text-error">{error}</div>
                        ) : fileUrl && activePage ? (
                            // Pass both the image URL and the pre-calculated words down
                            <DocumentViewer 
                                fileUrl={fileUrl} 
                                words={activePage.words} 
                            />
                        ) : null}
                    </div>
                </div>

                {/* === THE DRAGGABLE DIVIDER === */}
                <div
                    className="group relative flex w-3 cursor-col-resize items-center justify-center transition-colors hover:bg-primary/10 active:bg-primary/20"
                    onMouseDown={handleMouseDown}
                >
                    <div className="h-12 w-1 rounded-full bg-outline-variant transition-colors group-hover:bg-primary group-active:bg-primary" />
                </div>

                {/* === RIGHT SIDE: Extraction Workspace === */}
                <div
                    className="flex h-full flex-col p-6 transition-[width] duration-0"
                    style={{ width: `${100 - leftWidth}%` }}
                >
                    <div className="mb-6 space-y-1">
                        <h1 className="font-display-sm text-primary">Extraction Output</h1>
                        <p className="font-body-sm text-on-surface-variant">
                            Session ID: <span className="font-mono text-xs">{id}</span>
                        </p>
                    </div>

                    <div className="flex-1 overflow-auto rounded-2xl border border-dashed border-outline-variant bg-surface-container-lowest p-6">
                        {isLoading ? (
                            <div className="flex h-full items-center justify-center font-body-md text-on-surface-variant">
                                Awaiting extraction...
                            </div>
                        ) : activePage ? (
                            <div className="whitespace-pre-wrap font-body-md text-on-surface">
                                {activePage.text}
                            </div>
                        ) : null}
                    </div>
                </div>

            </div>
        </main>
    );
}